In [2]:
import numpy as np
import pandas as pd

#### Create a 2D array and print the dim and shape 

In [30]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
a1.shape

(2, 4)


In [14]:
a1.ndim

2

#### Create an array of 20 numbers using arange function and slice the values between 10 to 15 

In [31]:
list2 = np.arange(0,20)
a2 = slice(10,15,2)
print(list2[a2])

[10 12 14]


#### Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
Addition, 
Subtraction, 
Multiplication, 
Division

In [32]:
a3=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9],[1,4,3,6,6],[2,4,3,1,2]])
print(a3)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]
 [1 4 3 6 6]
 [2 4 3 1 2]]


In [33]:
a4=np.array([[5,4,3,2,1],[6,5,4,3,2],[7,6,5,4,3],[8,7,6,5,4],[5,6,7,8,9],[2,4,3,1,2],[1,4,3,6,6]])
print(a4)

[[5 4 3 2 1]
 [6 5 4 3 2]
 [7 6 5 4 3]
 [8 7 6 5 4]
 [5 6 7 8 9]
 [2 4 3 1 2]
 [1 4 3 6 6]]


#### Addition 

In [56]:
x = a3+a4
print(x)

[[ 6  6  6  6  6]
 [ 8  8  8  8  8]
 [10 10 10 10 10]
 [12 12 12 12 12]
 [10 12 14 16 18]
 [ 3  8  6  7  8]
 [ 3  8  6  7  8]]


#### Subtraction 

In [57]:
y = a3-a4
print(y)

[[-4 -2  0  2  4]
 [-4 -2  0  2  4]
 [-4 -2  0  2  4]
 [-4 -2  0  2  4]
 [ 0  0  0  0  0]
 [-1  0  0  5  4]
 [ 1  0  0 -5 -4]]


#### Multiplication

In [58]:
z = a3*a4
print(z)

[[ 5  8  9  8  5]
 [12 15 16 15 12]
 [21 24 25 24 21]
 [32 35 36 35 32]
 [25 36 49 64 81]
 [ 2 16  9  6 12]
 [ 2 16  9  6 12]]


#### Divide

In [60]:
w = a3/a4
print(w)

[[0.2        0.5        1.         2.         5.        ]
 [0.33333333 0.6        1.         1.66666667 3.        ]
 [0.42857143 0.66666667 1.         1.5        2.33333333]
 [0.5        0.71428571 1.         1.4        2.        ]
 [1.         1.         1.         1.         1.        ]
 [0.5        1.         1.         6.         3.        ]
 [2.         1.         1.         0.16666667 0.33333333]]


#### Create 2 incompatible arrays for broadcast and print out the error 

In [71]:
b1=([[1,2,3],[4,5,6]])
b2=([['a','b'],['c','d']])
t=b1*b2
t

TypeError: can't multiply sequence by non-int of type 'list'

#### Create two arrays of any dimension and perform vstack and hstack
 

In [72]:
b3=np.array([[5,4,3,2,1],[6,5,4,3,2],[7,6,5,4,3]])
b3

array([[5, 4, 3, 2, 1],
       [6, 5, 4, 3, 2],
       [7, 6, 5, 4, 3]])

In [73]:
b4=np.array([[8,7,6,5,4],[5,6,7,8,9],[2,4,3,1,2]])
b4

array([[8, 7, 6, 5, 4],
       [5, 6, 7, 8, 9],
       [2, 4, 3, 1, 2]])

In [76]:
np.vstack([b3,b4])

array([[5, 4, 3, 2, 1],
       [6, 5, 4, 3, 2],
       [7, 6, 5, 4, 3],
       [8, 7, 6, 5, 4],
       [5, 6, 7, 8, 9],
       [2, 4, 3, 1, 2]])

In [77]:
np.hstack([b3,b4])

array([[5, 4, 3, 2, 1, 8, 7, 6, 5, 4],
       [6, 5, 4, 3, 2, 5, 6, 7, 8, 9],
       [7, 6, 5, 4, 3, 2, 4, 3, 1, 2]])

#### Append two arrays using axis = 0 and axis = 1 

In [104]:
b5 = np.array([[1,2,3,4],[5,6,7,8]])
print('Appending using axis=0')
print(np.append(b5,([[10,20,30,40],[50,60,70,80]]),axis=0))

print(
      
      )

print('Appending using axis=1')
print(np.append(b5,([[10,20,30,40],[50,60,70,80]]),axis=1))

Appending using axis=0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]

Appending using axis=1
[[ 1  2  3  4 10 20 30 40]
 [ 5  6  7  8 50 60 70 80]]


#### Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation 

In [120]:
list1=[['Robert',15,'M','Yes'],['Gill',13,'M','No'],['Susan',14,'F','Yes'],
      ['Jenn',15,'F','Yes'],['William',14,'M','Yes'],['John',12,'M','Yes'],
      ['Kathryn',14,'F','Yes'],['Mary',13,'F','No']]
df1 = pd.DataFrame(list1,index=['1.','2.','3.','4.','5.','6.','7.','8.'],columns=['Name','Age','Gender','Dance ?'])
df1

Name  Age Gender Dance ?
1.   Robert   15      M     Yes
2.     Gill   13      M      No
3.    Susan   14      F     Yes
4.     Jenn   15      F     Yes
5.  William   14      M     Yes
6.     John   12      M     Yes
7.  Kathryn   14      F     Yes
8.     Mary   13      F      No

#### Create a dataframe of 4 X 8 dimension using a dictionary

In [10]:
dict1={'Name':['Rahul','Pranesh','Sakshi','Swapna'],'Eng.':[92,73,88,55],'Tam.':[89,80,94,45],'Math.':[93,71,90,40],'Soc.':[92,63,95,38],
      'Sci':[95,80,93,53],'French':[80,98,89,70],'C.Sci.':[85,90,80,90]}
df2=pd.DataFrame(dict1,index=[1,2,3,4])
3df2

Name  Eng.  Tam.  Math.  Soc.  Sci  French  C.Sci.
1    Rahul    92    89     93    92   95      80      85
2  Pranesh    73    80     71    63   80      98      90
3   Sakshi    88    94     90    95   93      89      80
4   Swapna    55    45     40    38   53      70      90

#### Use loc and iloc to subset the data for the above dataframe 

In [13]:
df2.loc[1:2,['Name','Eng.','Tam.']]

Name  Eng.  Tam.
1    Rahul    92    89
2  Pranesh    73    80

In [18]:
df2.iloc[:2,:3]

Name  Eng.  Tam.
1    Rahul    92    89
2  Pranesh    73    80

#### How to check the total number of notnull values in a column?


In [21]:
df2['Eng.'].notnull()

1    True
2    True
3    True
4    True
Name: Eng., dtype: bool

#### Create a dataframe with missing values and fill them all with 100

In [44]:
list3 = {'TV Sales':[90,120,80],'AC Sales':[80,90,110]}
df3 = pd.DataFrame(list3,index=['Onida','Samsung','Panasonic'])
df3

TV Sales  AC Sales
Onida            90        80
Samsung         120        90
Panasonic        80       110

In [45]:
df4=df3.reindex(['Onida','LG','Samsung','Videocon','Panasonic'])
df4

TV Sales  AC Sales
Onida          90.0      80.0
LG              NaN       NaN
Samsung       120.0      90.0
Videocon        NaN       NaN
Panasonic      80.0     110.0

In [46]:
df4.fillna(100,inplace=True)
df4

TV Sales  AC Sales
Onida          90.0      80.0
LG            100.0     100.0
Samsung       120.0      90.0
Videocon      100.0     100.0
Panasonic      80.0     110.0

#### Create a dataframe with missing values and drop the null records

In [47]:
df5=df3.reindex(['Onida','LG','Samsung','Videocon','Panasonic'])
df5

TV Sales  AC Sales
Onida          90.0      80.0
LG              NaN       NaN
Samsung       120.0      90.0
Videocon        NaN       NaN
Panasonic      80.0     110.0

In [48]:
df5.dropna()

TV Sales  AC Sales
Onida          90.0      80.0
Samsung       120.0      90.0
Panasonic      80.0     110.0

#### Perform aggregation task on below table

In [54]:
list4 = {'Age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
         'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black',
                      'Brown','Black','Blond','Black','Brown'],
         'U.S. Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast',
                       'Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest',
                       'Southeast'],
        'Validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}
df6 = pd.DataFrame(list4)
df6

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

####  Average age group by Regrion

In [62]:
df6.groupby(['U.S. Region'])['Age'].mean()

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [65]:
import warnings
warnings.filterwarnings('ignore')

#### sum of Age and Validation group by Hair color and then reset the index

In [69]:
df6.groupby(['Hair Color'])['Age','Validation'].sum().reset_index()

Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

####  Mean and the Median of Age group by Region

In [74]:
df6.groupby(['U.S. Region'])['Age'].agg([np.mean,np.median]).reset_index()

U.S. Region       mean  median
0   Northeast  32.750000    31.0
1   Northwest  40.500000    40.5
2   Southeast  31.000000    25.5
3   Southwest  29.857143    25.0

#### Split the  table into half and perform merge (inner, left and right) on Region.
#### One example for each type of merge (inner, left and right) 

In [130]:
df_left =pd.DataFrame ({'Age':[21,24,48,22,27,28,21,51,23],
         'Hair Color':['Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
         'U.S. Region':['Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest',
                       'Southeast'],
        'Validation':[1,0,1,0,0,1,1,0,1]})
df_left

Age Hair Color U.S. Region  Validation
0   21      Blond   Southwest           1
1   24      Blond   Northeast           0
2   48      Black   Southwest           1
3   22      Black   Southwest           0
4   27      Brown   Northeast           0
5   28      Black   Southeast           1
6   21      Blond   Southeast           1
7   51      Black   Northwest           0
8   23      Brown   Southeast           1

In [131]:
df_right = pd.DataFrame({'Age':[25,30,45,35,33,35,25,52],
         'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown'],
         'U.S. Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast'],
        'Validation':[1,0,0,0,1,1,0,1]})
df_right

Age Hair Color U.S. Region  Validation
0   25      Black   Southwest           1
1   30      Black   Northwest           0
2   45        Red   Northeast           0
3   35      Blond   Southwest           0
4   33      Brown   Southwest           1
5   35      Brown   Northeast           1
6   25      Black   Southwest           0
7   52      Brown   Southeast           1

In [132]:
df_left.merge(df_right, on='U.S. Region', how='left')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      21        Blond   Southwest             1     25        Black   
1      21        Blond   Southwest             1     35        Blond   
2      21        Blond   Southwest             1     33        Brown   
3      21        Blond   Southwest             1     25        Black   
4      24        Blond   Northeast             0     45          Red   
5      24        Blond   Northeast             0     35        Brown   
6      48        Black   Southwest             1     25        Black   
7      48        Black   Southwest             1     35        Blond   
8      48        Black   Southwest             1     33        Brown   
9      48        Black   Southwest             1     25        Black   
10     22        Black   Southwest             0     25        Black   
11     22        Black   Southwest             0     35        Blond   
12     22        Black   Southwest             0     33        Brown   
13     22        Black   Southwest             0     25        Black   
14     27        Brown   Northeast             0     45          Red   
15     27        Brown   Northeast             0     35        Brown   
16     28        Black   Southeast             1     52        Brown   
17     21        Blond   Southeast             1     52        Brown   
18     51        Black   Northwest             0     30        Black   
19     23        Brown   Southeast             1     52        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              0  
5              1  
6              1  
7              0  
8              1  
9              0  
10             1  
11             0  
12             1  
13             0  
14             0  
15             1  
16             1  
17             1  
18             0  
19             1

In [133]:
df_right.merge(df_left,on='U.S. Region',how='right')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     21        Blond   
1      35        Blond   Southwest             0     21        Blond   
2      33        Brown   Southwest             1     21        Blond   
3      25        Black   Southwest             0     21        Blond   
4      45          Red   Northeast             0     24        Blond   
5      35        Brown   Northeast             1     24        Blond   
6      25        Black   Southwest             1     48        Black   
7      35        Blond   Southwest             0     48        Black   
8      33        Brown   Southwest             1     48        Black   
9      25        Black   Southwest             0     48        Black   
10     25        Black   Southwest             1     22        Black   
11     35        Blond   Southwest             0     22        Black   
12     33        Brown   Southwest             1     22        Black   
13     25        Black   Southwest             0     22        Black   
14     45          Red   Northeast             0     27        Brown   
15     35        Brown   Northeast             1     27        Brown   
16     52        Brown   Southeast             1     28        Black   
17     52        Brown   Southeast             1     21        Blond   
18     30        Black   Northwest             0     51        Black   
19     52        Brown   Southeast             1     23        Brown   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

In [134]:
pd.merge(df_left, df_right,on='U.S. Region', how='inner')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      21        Blond   Southwest             1     25        Black   
1      21        Blond   Southwest             1     35        Blond   
2      21        Blond   Southwest             1     33        Brown   
3      21        Blond   Southwest             1     25        Black   
4      48        Black   Southwest             1     25        Black   
5      48        Black   Southwest             1     35        Blond   
6      48        Black   Southwest             1     33        Brown   
7      48        Black   Southwest             1     25        Black   
8      22        Black   Southwest             0     25        Black   
9      22        Black   Southwest             0     35        Blond   
10     22        Black   Southwest             0     33        Brown   
11     22        Black   Southwest             0     25        Black   
12     24        Blond   Northeast             0     45          Red   
13     24        Blond   Northeast             0     35        Brown   
14     27        Brown   Northeast             0     45          Red   
15     27        Brown   Northeast             0     35        Brown   
16     28        Black   Southeast             1     52        Brown   
17     21        Blond   Southeast             1     52        Brown   
18     23        Brown   Southeast             1     52        Brown   
19     51        Black   Northwest             0     30        Black   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             1  
11             0  
12             0  
13             1  
14             0  
15             1  
16             1  
17             1  
18             1  
19             0

####  Split the below table and perform concat row wise and column wise
 

In [135]:
pd.concat([df_left,df_right])

Age Hair Color U.S. Region  Validation
0   21      Blond   Southwest           1
1   24      Blond   Northeast           0
2   48      Black   Southwest           1
3   22      Black   Southwest           0
4   27      Brown   Northeast           0
5   28      Black   Southeast           1
6   21      Blond   Southeast           1
7   51      Black   Northwest           0
8   23      Brown   Southeast           1
0   25      Black   Southwest           1
1   30      Black   Northwest           0
2   45        Red   Northeast           0
3   35      Blond   Southwest           0
4   33      Brown   Southwest           1
5   35      Brown   Northeast           1
6   25      Black   Southwest           0
7   52      Brown   Southeast           1

In [136]:
pd.concat([df_left,df_right],axis=1)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   21      Blond   Southwest           1  25.0      Black   Southwest   
1   24      Blond   Northeast           0  30.0      Black   Northwest   
2   48      Black   Southwest           1  45.0        Red   Northeast   
3   22      Black   Southwest           0  35.0      Blond   Southwest   
4   27      Brown   Northeast           0  33.0      Brown   Southwest   
5   28      Black   Southeast           1  35.0      Brown   Northeast   
6   21      Blond   Southeast           1  25.0      Black   Southwest   
7   51      Black   Northwest           0  52.0      Brown   Southeast   
8   23      Brown   Southeast           1   NaN        NaN         NaN   

   Validation  
0         1.0  
1         0.0  
2         0.0  
3         0.0  
4         1.0  
5         1.0  
6         0.0  
7         1.0  
8         NaN

## End of Assignment